package com.s6x.pokeapp.models.entities;

public enum Ability {
	 // OBTENIDO DE : https://pokeapi.co/api/v2/ability/
    STENCH,
    DRIZZEL,
    SPEED_BOOST,
    BATTLE_ARMOR,
    STURDY, 
    DAMP, 
    LIMBER, 
    SAND_VEIL, 
    STATIC, 
    VOLT_ABSORB,
    WATER_ABSORB, 
    OBLIVIOUS, 
    CLOUD_NINE, 
    COMPOUND_EYES,
    INSOMNIA,
    INTIMIDATE,
    COLOR_CHANGE,
    CUTE_CHARM,
    IMMUNITY, 
    FLASH_FIRE, 
    SHIELD_DUST,
    SUCTION_CUPS,
    SAND_STREAM,
    OWN_TEMPO,
    NATURAL_CURE,
    BLAZE,
    BIG_PECKS,
    INNER_FOCUS,
    SHED_SKIN,
    RUN_AWAY,
    MINUS,
    MAGICIAN,
    TORRENT,
    THICK_FAT,
    PICKUP,
    PRESSURE,
    RIVALRY,
    FULL_METAL_BODY,
    VICTORY_STAR,
    POISON_POINT,
    OVERGROW
}
