export const pokemons = [
    {
        "id": 1,
        "name": "Absol",
        "avatar": "Absol.png",
        "type": "DARK",
        "ability": "STENCH",
        "level": 22,
        "health": 100,
        "health_max": 200,
        "coach": null
    },
    {
        "id": 2,
        "name": "Articuno",
        "avatar": "Articuno.png",
        "type": "ICE",
        "ability": "PRESSURE",
        "level": 22,
        "health": 100,
        "health_max": 200,
        "coach": null
    },
    {
        "id": 3,
        "name": "Bulbasaur",
        "avatar": "Bulbasaur.png",
        "type": "GRASS",
        "ability": "OVERGROW",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 4,
        "name": "Butterfree",
        "avatar": "Butterfree.png",
        "type": "BUG",
        "ability": "COMPOUND_EYES",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 5,
        "name": "Chansey",
        "avatar": "Chansey.png",
        "type": "NORMAL",
        "ability": "NATURAL_CURE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 6,
        "name": "Charizard",
        "avatar": "Charizard.png",
        "type": "FIRE",
        "ability": "BLAZE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 7,
        "name": "Ditto",
        "avatar": "Ditto.png",
        "type": "NORMAL",
        "ability": "LIMBER",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 8,
        "name": "Dragonair",
        "avatar": "Dragonair.png",
        "type": "DRAGON",
        "ability": "SHED_SKIN",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 9,
        "name": "Dragonite",
        "avatar": "Dragonite.png",
        "type": "DRAGON",
        "ability": "INNER_FOCUS",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 10,
        "name": "Eevee",
        "avatar": "Eevee.png",
        "type": "NORMAL",
        "ability": "RUN_AWAY",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 11,
        "name": "Emolga",
        "avatar": "Emolga.png",
        "type": "ELECTRIC",
        "ability": "STATIC",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 12,
        "name": "Flareon",
        "avatar": "Flareon.png",
        "type": "FIRE",
        "ability": "FLASH_FIRE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 13,
        "name": "Fletchling",
        "avatar": "Fletchling.png",
        "type": "NORMAL",
        "ability": "BIG_PECKS",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 14,
        "name": "Herdier",
        "avatar": "Herdier.png",
        "type": "NORMAL",
        "ability": "INTIMIDATE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 15,
        "name": "Hoopa",
        "avatar": "Hoopa.png",
        "type": "PSYCHIC",
        "ability": "MAGICIAN",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 16,
        "name": "Jigglypuff",
        "avatar": "Jigglypuff.png",
        "type": "NORMAL",
        "ability": "CUTE_CHARM",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 17,
        "name": "Kecleon",
        "avatar": "Kecleon.png",
        "type": "NORMAL",
        "ability": "COLOR_CHANGE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 18,
        "name": "Krokorok",
        "avatar": "Krokorok.png",
        "type": "GROUND",
        "ability": "INTIMIDATE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 19,
        "name": "Lapras",
        "avatar": "Lapras.png",
        "type": "WATER",
        "ability": "WATER_ABSORB",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 20,
        "name": "Marill",
        "avatar": "Marill.png",
        "type": "WATER",
        "ability": "THICK_FAT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 21,
        "name": "Meowth",
        "avatar": "Meowth.png",
        "type": "NORMAL",
        "ability": "PICKUP",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 22,
        "name": "Minccino",
        "avatar": "Minccino.png",
        "type": "NORMAL",
        "ability": "CUTE_CHARM",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 23,
        "name": "Minun",
        "avatar": "Minun.png",
        "type": "ELECTRIC",
        "ability": "MINUS",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 24,
        "name": "Moltres",
        "avatar": "Moltres.png",
        "type": "FIRE",
        "ability": "PRESSURE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 25,
        "name": "Mudkip",
        "avatar": "Mudkip.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 26,
        "name": "Nidoqueen",
        "avatar": "Nidoqueen.png",
        "type": "POISON",
        "ability": "POISON_POINT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 27,
        "name": "Ooctillery",
        "avatar": "Ooctillery.png",
        "type": "WATER",
        "ability": "SUCTION_CUPS",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 28,
        "name": "Oshawott",
        "avatar": "Oshawott.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 29,
        "name": "Pachirisu",
        "avatar": "Pachirisu.png",
        "type": "ELECTRIC",
        "ability": "RUN_AWAY",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 30,
        "name": "Persa",
        "avatar": "Persa.png",
        "type": "NORMAL",
        "ability": "LIMBER",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 31,
        "name": "Phanpy",
        "avatar": "Phanpy.png",
        "type": "GROUND",
        "ability": "PICKUP",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 32,
        "name": "Pikachu",
        "avatar": "Pikachu.png",
        "type": "ELECTRIC",
        "ability": "STATIC",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": {
            "id": 1,
            "username": "ASH",
            "pokemons": []
        }
    },
    {
        "id": 33,
        "name": "Piplup",
        "avatar": "Piplup.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 34,
        "name": "Popplio",
        "avatar": "Popplio.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 35,
        "name": "Pyroar",
        "avatar": "Pyroar.png",
        "type": "FIRE",
        "ability": "RIVALRY",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 36,
        "name": "Quilava",
        "avatar": "Quilava.png",
        "type": "FIRE",
        "ability": "BLAZE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 37,
        "name": "Rowlet",
        "avatar": "Rowlet.png",
        "type": "GRASS",
        "ability": "OVERGROW",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 38,
        "name": "Sandshrew",
        "avatar": "Sandshrew.png",
        "type": "GROUND",
        "ability": "SAND_VEIL",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 39,
        "name": "Shinx",
        "avatar": "Shinx.png",
        "type": "ELECTRIC",
        "ability": "RIVALRY",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 40,
        "name": "Skitty",
        "avatar": "Skitty.png",
        "type": "NORMAL",
        "ability": "CUTE_CHARM",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 41,
        "name": "Sneasel",
        "avatar": "Sneasel.png",
        "type": "DARK",
        "ability": "INNER_FOCUS",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 42,
        "name": "Solgaleo",
        "avatar": "Solgaleo.png",
        "type": "PSYCHIC",
        "ability": "FULL_METAL_BODY",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 43,
        "name": "Squirtle",
        "avatar": "Squirtle.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 44,
        "name": "Tepik",
        "avatar": "Tepik.png",
        "type": "FIRE",
        "ability": "BLAZE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 45,
        "name": "Totodile",
        "avatar": "Totodile.png",
        "type": "WATER",
        "ability": "TORRENT",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 46,
        "name": "Treecko",
        "avatar": "Treecko.png",
        "type": "GRASS",
        "ability": "OVERGROW",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 47,
        "name": "Turtwig",
        "avatar": "Turtwig.png",
        "type": "GRASS",
        "ability": "OVERGROW",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 48,
        "name": "Typhlosion",
        "avatar": "Typhlosion.png",
        "type": "FIRE",
        "ability": "BLAZE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 49,
        "name": "Tyranitar",
        "avatar": "Tyranitar.png",
        "type": "ROCK",
        "ability": "SAND_STREAM",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 50,
        "name": "Vaporeon",
        "avatar": "Vaporeon.png",
        "type": "WATER",
        "ability": "WATER_ABSORB",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 51,
        "name": "Venusaur",
        "avatar": "Venusaur.png",
        "type": "GRASS",
        "ability": "OVERGROW",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 52,
        "name": "Victini",
        "avatar": "Victini.png",
        "type": "PSYCHIC",
        "ability": "VICTORY_STAR",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 53,
        "name": "Vivillon",
        "avatar": "Vivillon.png",
        "type": "BUG",
        "ability": "SHIELD_DUST",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    },
    {
        "id": 54,
        "name": "Zapdos",
        "avatar": "Zapdos.png",
        "type": "ELECTRIC",
        "ability": "PRESSURE",
        "level": 25,
        "health": 300,
        "health_max": 400,
        "coach": null
    }
]